inherit_gem:
  gc_ruboconfig: rubocop.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/MethodLength:
  Max: 15

# Even after some serious refactoring, the default of 15 can be hard to meet
# if you favour saving intermediate state into well-named variables
Metrics/AbcSize:
  Max: 20

Style/RescueStandardError:
  Exclude:
    - "*/**/*_spec.rb"

Naming/MethodParameterName:
  AllowedNames:
    # These are the default allowed names, set by Rubocop
    - io
    - id
    # These are some custom names that we want to allow, since they aren't
    # uncommunicative - they're actually rather meaningful!
    - as

Gemspec/RequiredRubyVersion:
  Enabled: False

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
