version: 2

references:
  steps: &steps
    - checkout

    - run: gem install bundler -v 1.11.2

    - run: bundle install --path vendor/bundle

    - type: shell
      command: |
        bundle exec rspec --profile 10 \
                          --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format progress \
                          spec

    - type: store_test_results
      path: /tmp/test-results

    - run: bundle exec rubocop
jobs:
  build-ruby26-rails515:
    docker:
      - image: ruby:2.6
        environment:
          - RAILS_VERSION=5.1.5
    steps: *steps
  build-ruby27-rails515:
    docker:
      - image: ruby:2.7
        environment:
          - RAILS_VERSION=5.1.5
    steps: *steps
  build-ruby27-rails604:
    docker:
      - image: ruby:2.7
        environment:
          - RAILS_VERSION=6.0.4
    steps: *steps
  build-ruby27-rails614:
    docker:
      - image: ruby:2.7
        environment:
          - RAILS_VERSION=6.1.4
    steps: *steps
  build-ruby30-rails614:
    docker:
      - image: ruby:3.0
        environment:
          - RAILS_VERSION=6.1.4
    steps: *steps

workflows:
  version: 2
  tests:
    jobs:
      - build-ruby26-rails515
      - build-ruby27-rails515
      - build-ruby27-rails604
      - build-ruby27-rails614
      - build-ruby30-rails614
